# AUTH API

### POST: Register (Successful)
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
    "name": "Tuan",
    "username": "h4@gmail.com",
    "password": "tuan2004"
}

### POST: Login (Successful)
# Lưu trữ refresh token ở cookie, hết hạn sau 1 ngày
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "username": "tuantest@gmail.com",
    "password": "tuan2004"
}


#########################################################

# RESIDENT API

### POST: Tạo cư dân (Successful)
POST  http://localhost:8080/api/v1/residents
Content-Type: application/json

{
    "id": 2,
    "name": "Nguyen Van A",
    "dob": "2004-02-04",
    "status": "Resident"
}

### GET: Lấy thông tin các cư dân (Successful)
GET http://localhost:8080/api/v1/residents?size=5&page=0

# Descriptiton: ?size=5&page=0, số lượng kết quả trả về mỗi trang là 5 (trả về 5 cư dân mỗi khi gọi API)
# Bắt đầu từ trang 0 (Ví dụ 10 cư dân, thì định nghĩa 5-1 sẽ trả về 5 dân cư ở cuối)


#########################################################

# APARTMENT API

### POST: Tạo căn hộ (Successfull)
POST http://localhost:8080/api/v1/apartments
Content-Type: application/json

# Chưa có thêm phương tiện ở đây
{
    "addressNumber":"102",
    "area":"200",
    "status":"Business",
    "ownerId":"2",
    "ownerPhone":"0987654321",
    "memberIds":[2]
}

### GET: Lấy all thông tin căn hộ (Successfull) 
GET http://localhost:8080/api/v1/apartments